// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRZD_kQJ0xzM2kQHEE8gIaDnfgbh8pEb8',
    appId: '1:195095990413:web:98e57f95149700310a92c4',
    messagingSenderId: '195095990413',
    projectId: 'loginpage-1a978',
    authDomain: 'loginpage-1a978.firebaseapp.com',
    storageBucket: 'loginpage-1a978.firebasestorage.app',
    measurementId: 'G-H0QL6L7JEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIF0MSVQHPUCaEoVnCyvfeOnf_vW81VVE',
    appId: '1:195095990413:android:ab80021ee87e6ea70a92c4',
    messagingSenderId: '195095990413',
    projectId: 'loginpage-1a978',
    storageBucket: 'loginpage-1a978.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZBktMrnhrXIjS481PpaD5QbJ9-GhxrWE',
    appId: '1:195095990413:ios:b54d2855597a51ea0a92c4',
    messagingSenderId: '195095990413',
    projectId: 'loginpage-1a978',
    storageBucket: 'loginpage-1a978.firebasestorage.app',
    iosClientId: '195095990413-3sth2k47kmgp781i0ojemiirkap8001v.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZBktMrnhrXIjS481PpaD5QbJ9-GhxrWE',
    appId: '1:195095990413:ios:b54d2855597a51ea0a92c4',
    messagingSenderId: '195095990413',
    projectId: 'loginpage-1a978',
    storageBucket: 'loginpage-1a978.firebasestorage.app',
    iosClientId: '195095990413-3sth2k47kmgp781i0ojemiirkap8001v.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRZD_kQJ0xzM2kQHEE8gIaDnfgbh8pEb8',
    appId: '1:195095990413:web:08ad25048acc3d000a92c4',
    messagingSenderId: '195095990413',
    projectId: 'loginpage-1a978',
    authDomain: 'loginpage-1a978.firebaseapp.com',
    storageBucket: 'loginpage-1a978.firebasestorage.app',
    measurementId: 'G-YLPQBDF458',
  );
}
